[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version="0.3.0", features= ["glow"] }
rand = "0.8.4"
